# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1290, 839)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1251, 671))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(20, 20, 821, 551))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.MSTTAB = QtWidgets.QWidget()
        self.MSTTAB.setObjectName("MSTTAB")
        self.textEditMSTjson = QtWidgets.QTextEdit(self.MSTTAB)
        self.textEditMSTjson.setGeometry(QtCore.QRect(10, 20, 781, 481))
        self.textEditMSTjson.setObjectName("textEditMSTjson")
        self.tabWidget_2.addTab(self.MSTTAB, "")
        self.SEQTAB = QtWidgets.QWidget()
        self.SEQTAB.setObjectName("SEQTAB")
        self.textEditSEQjson = QtWidgets.QTextEdit(self.SEQTAB)
        self.textEditSEQjson.setGeometry(QtCore.QRect(10, 20, 781, 481))
        self.textEditSEQjson.setObjectName("textEditSEQjson")
        self.tabWidget_2.addTab(self.SEQTAB, "")
        self.SRTTTAB = QtWidgets.QWidget()
        self.SRTTTAB.setObjectName("SRTTTAB")
        self.textEditSRTTjson = QtWidgets.QTextEdit(self.SRTTTAB)
        self.textEditSRTTjson.setGeometry(QtCore.QRect(10, 20, 781, 481))
        self.textEditSRTTjson.setObjectName("textEditSRTTjson")
        self.tabWidget_2.addTab(self.SRTTTAB, "")
        self.pushButtonChangeStartEstimation = QtWidgets.QPushButton(self.tab)
        self.pushButtonChangeStartEstimation.setGeometry(QtCore.QRect(970, 620, 121, 23))
        self.pushButtonChangeStartEstimation.setObjectName("pushButtonChangeStartEstimation")
        self.checkBoxEstimateMST = QtWidgets.QCheckBox(self.tab)
        self.checkBoxEstimateMST.setGeometry(QtCore.QRect(960, 520, 161, 20))
        self.checkBoxEstimateMST.setObjectName("checkBoxEstimateMST")
        self.checkBoxEstimateSEQ = QtWidgets.QCheckBox(self.tab)
        self.checkBoxEstimateSEQ.setGeometry(QtCore.QRect(960, 550, 161, 20))
        self.checkBoxEstimateSEQ.setObjectName("checkBoxEstimateSEQ")
        self.checkBoxEstimateSRTT = QtWidgets.QCheckBox(self.tab)
        self.checkBoxEstimateSRTT.setGeometry(QtCore.QRect(960, 580, 161, 20))
        self.checkBoxEstimateSRTT.setObjectName("checkBoxEstimateSRTT")
        self.spinBoxMultiProcessor = QtWidgets.QSpinBox(self.tab)
        self.spinBoxMultiProcessor.setGeometry(QtCore.QRect(1090, 50, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBoxMultiProcessor.setFont(font)
        self.spinBoxMultiProcessor.setProperty("value", 6)
        self.spinBoxMultiProcessor.setObjectName("spinBoxMultiProcessor")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(860, 50, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(860, 70, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.lineEditTargetGroupFilePattern = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditTargetGroupFilePattern.setGeometry(QtCore.QRect(50, 100, 471, 22))
        self.lineEditTargetGroupFilePattern.setObjectName("lineEditTargetGroupFilePattern")
        self.lineEditTableFile = QtWidgets.QLineEdit(self.tab_3)
        self.lineEditTableFile.setGeometry(QtCore.QRect(30, 40, 521, 22))
        self.lineEditTableFile.setObjectName("lineEditTableFile")
        self.pushButtonAddTargetToTable = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonAddTargetToTable.setGeometry(QtCore.QRect(180, 180, 251, 28))
        self.pushButtonAddTargetToTable.setObjectName("pushButtonAddTargetToTable")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(50, 80, 131, 16))
        self.label_4.setObjectName("label_4")
        self.pushButtonChooseTableFile = QtWidgets.QPushButton(self.tab_3)
        self.pushButtonChooseTableFile.setGeometry(QtCore.QRect(580, 40, 93, 28))
        self.pushButtonChooseTableFile.setObjectName("pushButtonChooseTableFile")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(600, 100, 421, 192))
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.lineEditMainDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditMainDir.setGeometry(QtCore.QRect(20, 41, 741, 22))
        self.lineEditMainDir.setObjectName("lineEditMainDir")
        self.pushButtonChangeMainDir = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonChangeMainDir.setGeometry(QtCore.QRect(790, 41, 121, 23))
        self.pushButtonChangeMainDir.setObjectName("pushButtonChangeMainDir")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 0, 931, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButtonSaveConfig = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSaveConfig.setGeometry(QtCore.QRect(40, 760, 121, 23))
        self.pushButtonSaveConfig.setObjectName("pushButtonSaveConfig")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1290, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEditMSTjson.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">{</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_perform_analysis&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">       :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_estimate_network&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">       :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_perform_statistic&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">      :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_sim&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                    :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_estimate_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_test_Q_against_random&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">  :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;num_random_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_clustering&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;num_random_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;coupling_parameter&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">        :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0.3</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;resolution_parameter&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">      :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0.9</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;experiment_name&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;MST&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;path_inputfiles&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\MST</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;filepattern&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">                  :   [</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;REST1&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;REST2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;_ids&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">                         :   [</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;MST_G1&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;MST_G2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;sequence_length&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;path_outputfiles&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">Results2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;is_multiprocessing&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;show_images&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">                  :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;target_color&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">                 :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">0</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">     </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;table&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">                        :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#b4c973;\">Lernspiel_Auswertung_2020b.csv&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:8pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">}</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.MSTTAB), _translate("MainWindow", "MST"))
        self.textEditSEQjson.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">{</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_perform_analysis&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">       :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_estimate_network&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">       :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_perform_statistic&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">      :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_sim&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                    :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_estimate_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_test_Q_against_random&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">  :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;num_random_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_clustering&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;num_random_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;coupling_parameter&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">        :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0.3</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;resolution_parameter&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">      :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0.9</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;experiment_name&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;SEQ&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;path_inputfiles&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">SEQ8&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;filepattern&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">               :   [</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;FRA1&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;FRA2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;_ids&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                      :   [</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;SEQ8_G1&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;SEQ8_G2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    &quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">sequence_length&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">8</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;path_outputfiles&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">          :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Results&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_multiprocessing&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">        :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;show_images&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">               :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;target_color&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">8</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">    &quot;table&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                     :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Lernspiel_Auswertung_2020b.csv&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">}</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.SEQTAB), _translate("MainWindow", "SEQ"))
        self.textEditSRTTjson.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">{</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">    &quot;is_perform_analysis&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">       :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_estimate_network&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">       :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_perform_statistic&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">      :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_sim&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                    :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_estimate_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_test_Q_against_random&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">  :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">True</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;num_random_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_clustering&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">             :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;num_random_Q&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;coupling_parameter&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">        :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0.3</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;resolution_parameter&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">      :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0.9</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;experiment_name&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;MST&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;path_inputfiles&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">MST&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;filepattern&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">               :   [</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;REST1&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;REST2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;_ids&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                      :   [</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;MST_G1&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">, </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;MST_G2&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">],</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;sequence_length&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">           :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">10</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;path_outputfiles&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">          :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Results&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;is_multiprocessing&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">        :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;show_images&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">               :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#6c99bb;\">False</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;target_color&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">              :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">0</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">    </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;table&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">                     :   </span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">&quot;.</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Data_Rogens</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#a1617a;\">\\\\</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#b4c973;\">Lernspiel_Auswertung_2020b.csv&quot;</span><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">,</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Consolas,Courier New,monospace\'; font-size:10pt; color:#d6d6d6;\">}</span></p></body></html>"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.SRTTTAB), _translate("MainWindow", "SRTT"))
        self.pushButtonChangeStartEstimation.setText(_translate("MainWindow", "start Estimation"))
        self.checkBoxEstimateMST.setText(_translate("MainWindow", "estimate MST"))
        self.checkBoxEstimateSEQ.setText(_translate("MainWindow", "estimate SEQ"))
        self.checkBoxEstimateSRTT.setText(_translate("MainWindow", "estimate SRTT"))
        self.label_2.setText(_translate("MainWindow", "Number of parallel Processes"))
        self.label_3.setText(_translate("MainWindow", "( if is_multiprocessing is True)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Estimation"))
        self.lineEditTargetGroupFilePattern.setText(_translate("MainWindow", "[\"MST_1\", \"MST_2\", \"MST_3\"]"))
        self.pushButtonAddTargetToTable.setText(_translate("MainWindow", "add target to table"))
        self.label_4.setText(_translate("MainWindow", "Target Group file pattern"))
        self.pushButtonChooseTableFile.setText(_translate("MainWindow", "choose table file"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Im Target Group file pattern sollte eine Liste an Filepattern stehen, welche die Unterschiedlichen Columns in der Tablle kennzeichnet</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">z.B. Grischek Paradigma</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Tag: alle Probanden machen  das gleiche,  -&gt; MST_1_1_5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Tag: drei unterschiedliche Paradigmen       -&gt; MST_2_1_5, MST_2_2_5, MST_2_3_5</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Tag: alle Probanden machen das gleiche    -&gt; MST 3_0_5</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-&gt; Die Doktoranden brauchen fuer jede der Experimente unterschiedliche Spalten </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[&quot;MST_1_1&quot;, &quot;MST_2_1&quot;, &quot;MST_2_2&quot;, &quot;MST_2_3&quot;, &quot;MST_3_0&quot;]</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-&gt; Die Doktoranden sollen tageweise Eintragungen haben  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">[&quot;MST_1&quot;, &quot;MST_2&quot;, &quot;MST_3&quot;]</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Entscheidend ist die Benennung der Files im Ordner Experiment_data</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Export"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Statistic"))
        self.lineEditMainDir.setText(_translate("MainWindow", ".\\\\Data_Rogens\\Results2"))
        self.pushButtonChangeMainDir.setText(_translate("MainWindow", "ChangeMainDir"))
        self.label.setText(_translate("MainWindow", "The Main Output directory where all Results and Configurations will be saved"))
        self.pushButtonSaveConfig.setText(_translate("MainWindow", "save config"))

